version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasky-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: tasky-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: tasky-redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAIN://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr PLAIN://redpanda:9092,OUTSIDE://localhost:29092
      - --pandaproxy-addr PLAIN://0.0.0.0:8082,OUTSIDE://0.0.0.0:28082
      - --advertise-pandaproxy-addr PLAIN://redpanda:8082,OUTSIDE://localhost:28082
    ports:
      - "29092:29092"
      - "28082:28082"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  sql_data:
  redis_data:
  redpanda_data:
